# This workflow will install Python dependencies, run tests and lint with a multiple versions of Python on multiple platforms
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint --recursive=y api --rcfile=.pylintrc
    - name: Test with pytest
      run: |
        pytest api/

  tag-new-versions:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 2
      - name: Apply tag
        uses: salsify/action-detect-and-tag-new-version@v2
        id: repo-tag
        with:
          version-command: |
            cat VERSION
      - name: Get Tag
        if: ${{ steps.repo-tag.outputs.tag }}
        run: |
          echo ${{ steps.repo-tag.outputs.tag }}

  update-changelog:
    runs-on: ubuntu-latest
    needs: [tag-new-versions]
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Update CHANGELOG
        run: |
          rm CHANGELOG.md
          bash git-changelog.sh > CHANGELOG.md
      - name: commit CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Automatic CHANGELOG Update [skip ci]
